In [3]:
import numpy as np

In [4]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [5]:
b = np.array([[1,7,20], [5, 8, 9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [6]:
b.ndim

2

In [7]:
a.ndim

1

In [8]:

b.shape

(2, 3)

In [9]:
a.dtype

dtype('int32')

In [10]:
x = np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

In [11]:
print(b)


[[ 1  7 20]
 [ 5  8  9]]


In [12]:
b[0,2]

20

In [13]:
b[0]

array([ 1,  7, 20])

In [14]:
b[0, 1:]

array([ 7, 20])

In [15]:
b[1, 1] = 18
b[1, 1]

18

In [16]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

In [17]:
# Tümü sıfır matris/dizi
dizi_s = np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Tümü aynı değer olan dizi
dizi1= np.full((4,4), 50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [19]:
dizi2 = np.random.rand(4,3)
dizi2

array([[0.1387139 , 0.01536093, 0.44439215],
       [0.856867  , 0.01141964, 0.03457002],
       [0.23978306, 0.19622877, 0.57813448],
       [0.41625027, 0.45384753, 0.8121505 ]])

In [20]:
dizi3 = np.random.randint(0,100,size=(5,5))
dizi3

array([[13, 54, 90, 68, 27],
       [ 9, 93, 27, 44, 23],
       [67, 76, 68, 52, 33],
       [ 0, 37, 18, 50, 37],
       [74, 95, 47, 41, 26]])

In [22]:

a = np.array([1,2,3])
b = a.copy()
b[0] = 90

print(a)

[1 2 3]


In [23]:
print(b)

[90  2  3]


In [24]:

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [25]:

a + 4

array([5, 6, 7, 8])

In [26]:
a * 2

array([2, 4, 6, 8])

In [27]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [28]:
a ** 2

array([ 1,  4,  9, 16])

In [29]:
dizi4 = np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.min(dizi4)

1

In [31]:
np.sum(dizi4)

21

In [ ]:
# dosyadan dizi yükleme 
filedata = np.genfromtxt('ornek.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)
filedata[1,0]